---
version: '3.3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks:
      dt-net:
        ipv4_address: 172.20.20.2
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    extra_hosts:
      - "moby:127.0.0.1"

  kafka:
    image: confluentinc/cp-kafka:latest
    networks:
      dt-net:
        ipv4_address: 172.20.20.3
    ports: 
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 172.20.20.2:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://172.20.20.3:9092
    extra_hosts:
      - "moby:127.0.0.1"

  publisher:
    image: acalderon88/javapublisher:latest
    networks:
      dt-net:
        ipv4_address: 172.20.20.4
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    environment:
      KAFKA_BROKERS: 172.20.20.3:9092

  consumer:
    image: acalderon88/pythonconsumer:latest
    networks:
      dt-net:
        ipv4_address: 172.20.20.5
    depends_on:
      - kafka
    environment:
      KAFKA_BROKERS: 172.20.20.3:9092
    volumes:
      - "/tmp/:/tmp/"

networks:
  dt-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.20.0/24
