---
version: '3.3'
services:
  talker:
    image: acalderon88/talker:latest
    networks:
      dt-net:
        ipv4_address: 172.20.20.2
    ports:
      - "8080:8080"
    environment:
      USER: EAFIT

  proxy:
    image: acalderon88/proxy:latest
    networks:
      dt-net:
        ipv4_address: 172.20.20.3
    ports: 
      - "9090:9090"
    depends_on:
      - talker
    volumes:
      - "/tmp/:/tmp/"

networks:
  dt-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.20.0/24
